### ISSUE TITLE
OPTALG solve crash

### ISSUE THREAD

**Issue by martinzellner** [ttinoco/OPTALG#1]
OPTALG `slove()` crashes with the following error (which is not caught as an Python Exception):

`lda must be >= MAX(N,1): lda=5 N=6BLAS error: Parameter number 7 passed to cblas_dtrsv had an invalid value`

Probably there is something odd with my matrix structure, however this should not lead to a crash without any Python output.

**Comment by ttinoco** [comment]
This is interesting. It would be helpful if you somehow give me that matrix
you are using so I can recreate the problem, fix the issue and add a
unittest.
Tomas

**Comment by martinzellner** [comment]
I hope saving the matrices worked:
[crash.npz.zip](https://github.com/ttinoco/OPTALG/files/254037/crash.npz.zip)

Here is what I do:
<img width="1113" alt="screen shot 2016-05-08 at 20 09 29" src="https://cloud.githubusercontent.com/assets/855054/15099601/fd9dd506-1559-11e6-8095-a66105beab02.png">

**Comment by martinzellner** [comment]
It might be platform specific though (OpenBLAS vs. Apple Accelerate)..

**Comment by ttinoco** [comment]
There are several odd things in the code above:
1) variables need to be specified before constructing a problem (as an example, see the DCOPF problem construction in GRIDOPT)
2)  generator Q participations are not needed since Q should not be variables,
3) generator P participations are needed when there is more than one generator connected to a bus (unless the objective function removes extra degrees of freedom)
4) you are missing the LBOUND constraint to get l <= Gx <= u with G=identity
5) p.gphi is not equal to the g argument of the QP problem. gphi(x) is equal to g + Hx
6) in your problem above, p.l and p.u are meaningless since no inequality constraints have been constructed.

**Comment by martinzellner** [comment]
Thanks for the remarks. I will change the code accordingly. Mostly your points are taken care of within the MPProblem class at the moment (e.g. variable definition). This needs to be changed, but the problem should not be affected by this.
Concerning 5): Can I get `g`somehow?

**Comment by ttinoco** [comment]
Yes, use the identity given in the previous comment: g + Hx = gphi(x),
solve for g

**Comment by martinzellner** [comment]
Just as a remark: The crash only occurs when I add the battery energy constraints. So I assume something is odd with my A matrix...

**Comment by martinzellner** [comment]
I could track it down further. This happens when a all-zero column appears in the A matrix (which shouldn't happen).
I think there should be an Exception complaining about the matrix being rank deficient.

**Comment by ttinoco** [comment]
It is not as simple as that. Rank of A is not the rank the optimization algorithm cares about, but the rank of the KKT matrix. I suspect the linear solver is throwing the error. The linear solver should be throwing a python exception. If not, then the wrapper has a bug (either superlu or mumps, I am not sure which one you are using). The wrappers are external to optalg. However, I am sure some checks can be added at the beginning of the solve method to check bad data easily. I will take care of this as soon as I have time.
